# Natural Language Processing

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('request_description_severity.csv')

In [ ]:
dataset.head()

request_description severity  severity_id
0             I have headache      one            1
1            I cannot breathe     nine            9
2  I have high blood pressure    seven            7
3           I have teeth ache      one            1
4        I have blured vision    seven            7

## Cleaning the texts

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 309):
  review = re.sub('[^a-zA-Z]', ' ', dataset['request_description'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
len(corpus)

309

## Creating the Bag of Words model

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

In [ ]:
import pickle

filename = 'bow_pickle.pickle'
pickle.dump(cv, open(filename, 'wb'))

In [ ]:
X[0].shape

(378,)

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

## Training the Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
import pickle

filename = 'GaussianNB_nlp_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 7]
 [7 8]
 [3 4]
 [9 9]
 [9 9]
 [9 9]
 [0 3]
 [4 5]
 [4 6]
 [8 7]
 [6 7]
 [2 3]
 [9 3]
 [9 5]
 [9 9]
 [3 7]
 [0 6]
 [9 9]
 [0 9]
 [7 7]
 [1 3]
 [6 7]
 [9 9]
 [0 5]
 [4 4]
 [8 9]
 [3 6]
 [5 9]
 [9 8]
 [3 8]
 [4 9]
 [7 1]
 [7 6]
 [0 1]
 [4 7]
 [6 8]
 [7 9]
 [9 8]
 [9 9]
 [1 9]
 [4 3]
 [6 8]
 [5 3]
 [1 3]
 [8 9]
 [8 5]
 [5 8]
 [9 9]
 [5 8]
 [2 9]
 [6 5]
 [4 8]
 [1 9]
 [9 8]
 [7 6]
 [5 9]
 [1 5]
 [7 9]
 [1 3]
 [2 8]
 [8 3]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 3 1 0 1 1 0 0 1 1]
 [0 0 0 1 1 0 0 0 0 0]
 [1 1 0 0 1 0 1 0 1 1]
 [1 0 0 1 1 0 0 2 0 0]
 [0 1 0 1 1 0 2 1 1 0]
 [0 0 1 1 1 2 2 1 0 3]
 [1 2 1 0 1 2 0 2 2 8]]


0.16129032258064516

## Prediction

In [ ]:
new_review = 'two trucks collided'
new_review = re.sub('[^a-zA-Z]', ' ', new_review)
new_review = new_review.lower()
new_review = new_review.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]
new_review = ' '.join(new_review)
new_corpus = [new_review]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred)

[8]
